stages:
  data_ingestion:
    cmd: src/ChickenDiseaseClassifier/pipeline/stage_01_dataingestion.py
    deps:
      - src/ChickenDiseaseClassifier/pipeline/stage_01_dataingestion.py
      - config/config.yaml
    outs:
      - artifacts/data_ingestion/Chicken-fecal-images

  
  prepare_base_model:
    cmd: src/ChickenDiseaseClassifier/pipeline/stage_02_prepare_base_model.py
    deps:
      - src/ChickenDiseaseClassifier/pipeline/stage_02_prepare_base_model.py
      - config/config.yaml
    params:
      - IMAGE_SIZE
      - INCLUDE_TOP
      - CLASSES
      - WEIGHTS
      - LEARNING_RATE
    outs:
      - artifacts/prepare_base_model

  
  model_training:
    cmd: src/ChickenDiseaseClassifier/pipeline/stage_02_prepare_base_model.py
    deps:
      - src/ChickenDiseaseClassifier/pipeline/stage_02_prepare_base_model.py
      - config/config.yaml
    params:
      - IMAGE_SIZE
      - INCLUDE_TOP
      - CLASSES
      - WEIGHTS
      - LEARNING_RATE
    outs:
      - artifacts/prepare_base_model

  