AUTHENTICATION: True
AUGUMENTATION: True
IMAGE_SIZE: [224, 224, 3] # as per VGG 16 model
BATCH_SIZE: 32
INCLUDE_TOP: False
EPOCHS: 40 # 100 kr lena baad m
CLASSES: 2
WEIGHTS: imagenet
LEARNING_RATE: 0.01
