artifacts_root: artifacts


# data ingestion 
data_ingestion:
  data_ingestion_root: artifacts/data_ingestion
  source_url: data/Chicken-fecal-images.zip
  local_data_file: artifacts/data_ingestion/data.zip
  unzip_dir: artifacts/data_ingestion


# prepare base model
prepare_base_model:
  prepare_base_model_root: artifacts/prepare_base_model
  base_model_path: artifacts/prepare_base_model/base_model.h5
  updated_base_model_path: artifacts/prepare_base_model/updated_base_model.h5




# prepare callbacks
prepare_callbacks:
  prepare_callbacks_root: artifacts/prepare_callbacks
  tensorboard_root_log_dir: artifacts/prepare_callbacks/tensorboard_log_dir
  checkpoint_model_filepath: artifacts/prepare_callbacks/checkpoint_dir/model.h5
  


# model trainer
training:
  root_dir: artifacts/training
  trained_model_path: artifacts/training/model.h5



