artifacts_root: artifacts


# data ingestion 
data_ingestion:
  data_ingestion_root: artifacts/data_ingestion
  source_url: data/Chicken-fecal-images.zip
  local_data_file: artifacts/data_ingestion/data.zip
  unzip_dir: artifacts/data_ingestion